services:
  codeproject-ai:
    image: codeproject/ai-server
    container_name: codeproject-ai
    restart: unless-stopped
    ports:
      - "32168:32168"
    volumes:
      - ./data:/etc/codeproject/ai
      - ./modules:/app/modules
